CREATE DATABASE inlock_games_tarde;
GO

USE inlock_games_tarde
GO

CREATE TABLE ESTUDIO (
	idEstudio SMALLINT PRIMARY KEY IDENTITY,
	nomeEstudio VARCHAR(50) NOT NULL
);
GO

CREATE TABLE JOGO (
	idJogo INT PRIMARY KEY IDENTITY,
	nomeJogo VARCHAR(60) NOT NULL UNIQUE,
	descricao VARCHAR(226) NOT NULL,
	dataLancamento SMALLDATETIME NOT NULL,
	valor SMALLMONEY NOT NULL,
	idEstudio SMALLINT FOREIGN KEY REFERENCES ESTUDIO(idEstudio)
);
GO

CREATE TABLE TIPOUSUARIO (
	idTipoUsuario TINYINT PRIMARY KEY IDENTITY,
	titulo VARCHAR(60) NOT NULL UNIQUE,
);
GO

CREATE TABLE USUARIO (
	idUsuario INT PRIMARY KEY IDENTITY,
	email VARCHAR(256) NOT NULL UNIQUE,
	senha VARCHAR(50) NOT NULL CHECK(LEN(senha) >= 3 AND LEN(SENHA) <= 8 ),
	idTipoUsuario TINYINT FOREIGN KEY REFERENCES TIPOUSUARIO(idTipoUsuario)
);
GO
